package ProyectoForm2;

import javax.swing.JOptionPane;
import javax.swing.text.*;
import java.text.DecimalFormatSymbols;

/* * @author
Luis Ezequiel Sosa
Lucas Saidman
Gimenez Diego Ruben
Carlos German Mecias Giacomelli
Tomas Migliozzi Badani
Luca Rodrigaño

Proyecto Conversor de temperaturas - TP3 Grupo 6 
Conversor de temperaturas entre Celsius, Fahrenheit, Kelvin y Rankine */
public class TP3Ejercicio2 extends javax.swing.JFrame {

    /**
     * Creates new form Jframe
     */
    public TP3Ejercicio2() {
        initComponents();
        String seleccionInicial = (String) CBoxSelectorDeTemperatura.getSelectedItem();
        rbCelsius.setEnabled(!seleccionInicial.equals("Celsius"));
        rbKelvin.setEnabled(!seleccionInicial.equals("Kelvin"));
        rbFahrenheit.setEnabled(!seleccionInicial.equals("Fahrenheit"));
        rbRankine.setEnabled(!seleccionInicial.equals("Rankine"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgMedida = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtGrados = new javax.swing.JTextField();
        lblTemperatura = new javax.swing.JLabel();
        rbFahrenheit = new javax.swing.JRadioButton();
        rbCelsius = new javax.swing.JRadioButton();
        rbKelvin = new javax.swing.JRadioButton();
        rbRankine = new javax.swing.JRadioButton();
        btnConvert = new javax.swing.JButton();
        CBoxSelectorDeTemperatura = new javax.swing.JComboBox<>();
        jBtmLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TP3 Grupo 6  De Celcius a Fahrenheit");
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(51, 153, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTitulo.setFont(new java.awt.Font("The Bold Font", 0, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 204, 204));
        lblTitulo.setText("    Conversor de temperaturas");
        lblTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtGrados.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtGrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradosActionPerformed(evt);
            }
        });

        lblTemperatura.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblTemperatura.setText("Ingrese temperatura en Grados");

        bgMedida.add(rbFahrenheit);
        rbFahrenheit.setText("A Fahrenheit");

        bgMedida.add(rbCelsius);
        rbCelsius.setText("A Celsius");
        rbCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCelsiusActionPerformed(evt);
            }
        });

        bgMedida.add(rbKelvin);
        rbKelvin.setText("A Kelvin");

        bgMedida.add(rbRankine);
        rbRankine.setText("A Rankine");

        btnConvert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/convert_icon.png"))); // NOI18N
        btnConvert.setText("Convertir");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });

        CBoxSelectorDeTemperatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Kelvin", "Fahrenheit", "Rankine" }));
        CBoxSelectorDeTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxSelectorDeTemperaturaActionPerformed(evt);
            }
        });

        jBtmLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_limpiar.png"))); // NOI18N
        jBtmLimpiar.setText("Limpiar");
        jBtmLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtmLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbCelsius)
                    .addComponent(rbRankine))
                .addGap(87, 87, 87))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(rbKelvin)
                                .addGap(68, 68, 68))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnConvert)
                                .addGap(35, 35, 35)))
                        .addComponent(jBtmLimpiar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(rbFahrenheit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(txtGrados, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CBoxSelectorDeTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)))
                .addGap(0, 38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblTemperatura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGrados, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(CBoxSelectorDeTemperatura))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFahrenheit)
                    .addComponent(rbCelsius))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbKelvin)
                    .addComponent(rbRankine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtmLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConvert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtGradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGradosActionPerformed

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
        // TODO add your handling code here:
        String seleccionTemperatura = (String) CBoxSelectorDeTemperatura.getSelectedItem(); //Obtengo el valor de el selector de temperatura

        try {
            double input = Double.parseDouble(txtGrados.getText());
            String resultado = "";
            double valueInCelsius;

            switch (seleccionTemperatura) {
                case "Celsius":
                    valueInCelsius = input;
                    break;
                case "Kelvin":
                    valueInCelsius = kelvinACelsius(input);
                    break;
                case "Fahrenheit":
                    valueInCelsius = fahrenheitACelsius(input);
                    break;
                case "Rankine":
                    valueInCelsius = rankineACelsius(input);
                    break;
                default:
                    valueInCelsius = input;
                    break;
            }

            if (rbFahrenheit.isSelected()) {
                resultado = "La temperatura en Fahrenheit es: " + celsiusAFahrenheit(valueInCelsius);
            } else if (rbCelsius.isSelected()) {
                resultado = "La temperatura en Celsius es: " + valueInCelsius;
            } else if (rbKelvin.isSelected()) {
                resultado = "La temperatura en Kelvin es: " + celsiusAKelvin(valueInCelsius);
            } else if (rbRankine.isSelected()) {
                resultado = "La temperatura en Rankine es: " + celsiusARankine(valueInCelsius);
            } else {
                resultado = "Por favor, selecciona una unidad para convertir.";
            }
            JOptionPane.showMessageDialog(this, resultado);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConvertActionPerformed

    //CALCULOS PARA CADA CONVERISION
    //CELSIUS
    private double celsiusAKelvin(Double c) {
        return (c + 273.15);
    }

    private double celsiusAFahrenheit(Double c) {
        return ((c * (9.0 / 5.0)) + 32);
    }

    private double celsiusARankine(double c) {
        return (c * 9.0 / 5.0) + 491.67;
    }

    //KELVIN
    private double kelvinAFahrenheit(Double k) {
        return (k - 273.15) * (9.0 / 5.0) + 32;
    }

    private double kelvinACelsius(Double k) {
        return k - 273.15;
    }

    private double kelvinARankine(double k) {
        return k * 1.8;
    }

    //FAHRENHEITS
    private double fahrenheitACelsius(Double f) {
        return (f - 32) * (5.0 / 9.0);
    }

    private double fahrenheitAKelvin(Double f) {
        return (f - 32) * (5.0 / 9.0) + 273.15;
    }

    private double fahrenheitARankine(double f) {
        return f + 459.67;
    }

    //RANKINE
    private double rankineACelsius(double r) {
        return (r - 491.67) * 5.0 / 9.0;
    }

    private double rankineAKelvin(double r) {
        return r / 1.8;
    }

    private double rankineAFahrenheit(double r) {
        return r - 459.67;
    }

    private void CBoxSelectorDeTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxSelectorDeTemperaturaActionPerformed
        // TODO add your handling code here:
        String seleccionTemperatura = (String) CBoxSelectorDeTemperatura.getSelectedItem();

        rbCelsius.setEnabled(true);
        rbKelvin.setEnabled(true);
        rbFahrenheit.setEnabled(true);
        rbRankine.setEnabled(true);

        switch (seleccionTemperatura) {
            case "Celsius":
                lblTemperatura.setText("Ingrese temperatura en Celsius");
                rbCelsius.setEnabled(false);
                break;
            case "Kelvin":
                lblTemperatura.setText("Ingrese temperatura en Kelvin");
                rbKelvin.setEnabled(false);
                break;
            case "Fahrenheit":
                lblTemperatura.setText("Ingrese temperatura en Fahrenheit");
                rbFahrenheit.setEnabled(false);
                break;
            case "Rankine":
                lblTemperatura.setText("Ingrese temperatura en Rankine");
                rbRankine.setEnabled(false);
                break;
            default:
                lblTemperatura.setText("Ingrese temperatura");
        }
        if ((rbCelsius.isSelected() && !rbCelsius.isEnabled()) || (rbKelvin.isSelected() && !rbKelvin.isEnabled()) || (rbFahrenheit.isSelected() && !rbFahrenheit.isEnabled()) || (rbRankine.isSelected() && !rbRankine.isEnabled())) {
            bgMedida.clearSelection();
        }

    }//GEN-LAST:event_CBoxSelectorDeTemperaturaActionPerformed

    private void rbCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCelsiusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCelsiusActionPerformed

    private void jBtmLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtmLimpiarActionPerformed
        txtGrados.setText("");
        bgMedida.clearSelection();
    }//GEN-LAST:event_jBtmLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TP3Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TP3Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TP3Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TP3Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TP3Ejercicio2().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBoxSelectorDeTemperatura;
    private javax.swing.ButtonGroup bgMedida;
    private javax.swing.JButton btnConvert;
    private javax.swing.JButton jBtmLimpiar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTemperatura;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbCelsius;
    private javax.swing.JRadioButton rbFahrenheit;
    private javax.swing.JRadioButton rbKelvin;
    private javax.swing.JRadioButton rbRankine;
    private javax.swing.JTextField txtGrados;
    // End of variables declaration//GEN-END:variables
}
